{
  "l": [
    {
      "name": "l1",
      "output": null
    },
    {
      "name": "l2",
      "output": null
    }
  ],
  "log_Map2": [
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    }
  ],
  "log_Map3": [
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    }
  ],
  "white_IP": [
    "127.0.0.1",
    "10.0.0.1",
    "127.0.0.1"
  ],
  "logMap": {
    "ap2": {
      "name": "appLog",
      "output": null
    },
    "app": {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    "app1": {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    "default": {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    },
    "server": {
      "name": "appLog",
      "output": [
        "stdio"
      ]
    }
  },
  "mode": "dev",
  "appName": "demoApp",
  "redis": {
    "host": "127.0.0.1",
    "port": 5678,
    "DB": 0,
    "enable": false
  }
}
